### ISSUE TITLE
Plop hangs and becomes unresponsive if no generator is specified

### ISSUE THREAD

**Issue by RyanWarner** [yawnch/react-firebase-ssr-starter#22]
Specifying a generator like `npx plop Component` works fine. `npx plop` crashes.

**Comment by RyanWarner** [comment]
Possibly related to Node version: https://github.com/amwmedia/plop/issues/75

**Comment by romansorin** [comment]
Issue seems to have been fixed @RyanWarner 

![](https://i.gyazo.com/0869aa93e98c1c7c4da4452be6591386.png)

**Comment by RyanWarner** [comment]
Indeed, this has been fixed by a recently released version of Plop!
